site_name: test-mkdocs.tiogars.fr
site_url: https://tiogars.github.io/mkdocs-docker-image
repo_name: tiogars/mkdocs-docker-image
repo_url: https://github.com/tiogars/mkdocs-docker-image
edit_uri: edit/main/docs/
site_description: Documentation for mkdocs-docker-image (test)
site_author: Tiogars
copyright: © 2025, Tiogars
site_dir: site_output
nav:
  - Home: index.md
  - Features: features/index.md
  - Requirements: requirements/index.md
  - Diagrams: diagrams/index.md
theme:
  # name: readthedocs
  favicon: assets/images/favicon.png
  icon:
    repo: fontawesome/brands/github
  name: material
  custom_dir: docs/overrides
  features:
    - content.action.edit
    - content.action.view  
  language: en
  locale: en
  highlightjs: true
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
plugins:
  # https://ultrabug.github.io/mkdocs-static-i18n/
  - i18n:
      # https://ultrabug.github.io/mkdocs-static-i18n/setup/choosing-the-structure/
      docs_structure: suffix
      # https://ultrabug.github.io/mkdocs-static-i18n/setup/controlling-your-builds/
      fallback_to_default: true
      # https://ultrabug.github.io/mkdocs-static-i18n/setup/setting-up-languages/
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: fr
          name: Français
          build: true
          nav_translations:
            Home: Accueil
            Features: Fonctionnalités
            Requirements: Prérequis
            Diagrams: Diagrammes
      # https://ultrabug.github.io/mkdocs-static-i18n/setup/setting-up-material/
      reconfigure_material: true
  - search:
  # https://pypi.org/project/mkdocs-include-markdown-plugin/
  - include-markdown:

  # https://pypi.org/project/mkdocs-kroki-plugin/
  - kroki:
      ServerURL: 'https://kroki.tiogars.fr'
      FencePrefix: 'kroki-'
      EnableBlockDiag: true
      EnableBpmn: false
      EnableExcalidraw: true
      EnableMermaid: true
      FailFast: false
      HttpMethod: POST
      FileTypes:
        - png
        - svg
      FileTypeOverrides:
        nwdiag: svg
        mermaid: png
  - macros:

  # https://pypi.org/project/mkdocs-with-pdf/
  - to-pdf:
      author: Tiogars
      back_cover: true
      copyright: Copyright © Tiogars 2025
      cover: true
      cover_logo: assets/images/favicon.png
      cover_subtitle: Documentation
      cover_title: mkdocs-docker-image
      debug_html: true
      output_path: fr.tiogars.mkdocs-docker-image-test.pdf
  - print-site:
      add_to_navigation: false
      print_page_title: 'Print Site'
      print_page_basename: 'print_page'
      add_print_site_banner: false
      # Table of contents
      add_table_of_contents: true
      toc_title: 'Table of Contents'
      toc_depth: 6
      # Content-related
      add_full_urls: true
      enumerate_headings: true
      enumerate_figures: true
      add_cover_page: true
      cover_page_template: ""
      path_to_pdf: "fr.tiogars.mkdocs-docker-image-test.pdf"
      include_css: true
      enabled: true
      exclude: []

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      #   # make exceptions to highlighting of code:
      # custom_fences:
      #   - name: mermaid
      #     class: mermaid
      #     format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
extra:
  alternate:
    - name: French
      link: /fr/ 
      lang: fr
    - name: English
      link: /en/
      lang: en
